[package]
name = "kukka"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.profiling]
inherits = "release" 
strip = false
debug = 1

[dependencies]
tikv-jemallocator = "0.6.0"
